version: '3.8'

services:
  osmo-stp:
    build: .
    container_name: osmo-stp
    ports:
      - "4239:4239"    # VTY interface
      - "2905:2905"    # M3UA
      - "14001:14001"  # SCCP
    volumes:
      - ./logs:/var/log/osmocom
    restart: unless-stopped
    networks:
      - ss7-network

  # VTY Proxy Server (enables real dashboard connection)
  vty-proxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    container_name: vty-proxy
    ports:
      - "5000:5000"    # VTY Proxy API
    depends_on:
      - osmo-stp
    environment:
      - VTY_HOST=osmo-stp
      - VTY_PORT=4239
    restart: unless-stopped
    networks:
      - ss7-network

  # Web Dashboard (now with real VTY connection)
  web-dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    container_name: ss7-dashboard
    ports:
      - "8888:80"      # Web Dashboard
    depends_on:
      - osmo-stp
      - vty-proxy
    restart: unless-stopped
    networks:
      - ss7-network

  # SMS Simulator Web Interface
  sms-simulator:
    build:
      context: .
      dockerfile: Dockerfile.sms
    container_name: sms-simulator
    ports:
      - "9999:80"      # SMS Simulator Interface
    depends_on:
      - osmo-stp
    restart: unless-stopped
    networks:
      - ss7-network

  # Optional: Add a test client container
  osmo-test-client:
    build: .
    container_name: osmo-test-client
    command: tail -f /dev/null  # Keep container running
    depends_on:
      - osmo-stp
    networks:
      - ss7-network
    profiles:
      - test

networks:
  ss7-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16